### ISSUE TITLE
Switching desktops misaligns the border

### ISSUE THREAD

**Issue by ThePixelDude111** [lukeyou05/tacky-borders#5]
Whenever I switch desktops, the borders just leave the window they're attached to
Before switching:
![Screenshot (28)](https://github.com/user-attachments/assets/1a6272e7-233b-4ba7-9ed6-196160ee6b3e)

After switching:
![Screenshot (27)](https://github.com/user-attachments/assets/1727114c-1047-4c65-a23b-21df76c411ba)

OS: Windows 10 22h2 (with rectify11 and explorerpatcher)

**Comment by lukeyou05** [comment]
Hi, what do you mean by switching desktops? And what version of tacky-borders are you running?

**Comment by ThePixelDude111** [comment]
> Hi, what do you mean by switching desktops? And what version of tacky-borders are you running?

I mean switching desktops from task view, or in my case, by touchpad gestures, and I'm running the latest version (0.2.0)

**Comment by lukeyou05** [comment]
Unfortunately, I can't reproduce the issue on either my laptop with touchpad gestures or on my desktop. Perhaps you could try the latest preview build here: https://github.com/lukeyou05/tacky-borders/releases/tag/v0.3.0-preview

**Comment by ThePixelDude111** [comment]
> Unfortunately, I can't reproduce the issue on either my laptop with touchpad gestures or on my desktop. This may just be a Windows 10 thing, and I don't have any machines running Windows 10 anymore. Perhaps you could try the latest preview build here: https://github.com/lukeyou05/tacky-borders/releases/tag/v0.3.0-preview

Ok I tried the latest preview and the issue is somehow gone, closing this issue.
