### ISSUE TITLE
An issue regarding animated multiple colors

### ISSUE THREAD

**Issue by RTFTR** [lukeyou05/tacky-borders#8]
Hi, I know i should not post this issue when the animation feature is not on public release,
But i think it'd be important to report this issue in advance.

When i set more than three colors, 
![image](https://github.com/user-attachments/assets/a7bde95c-1187-47bc-87be-c7d2eef0d77b)

It will crash tacky borders when a new window appears.

Here's the video:

https://github.com/user-attachments/assets/27a16739-44d8-4179-876b-753b841914ce

If you wonder what Windows build I am on:
![image](https://github.com/user-attachments/assets/a185a65e-f260-4772-a518-da60b44a56f6)

**Comment by RTFTR** [comment]
Here's the log:

`02:40:54 [DEBUG] (1) tacky_borders::utils: Creating border for: HWND(0x22076e)
thread '<unnamed>' panicked at src\animations.rs:253:65:
index out of bounds: the len is 2 but the index is 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core\src\panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7ff60aab0d61 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ff60aab0d61 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff60aab0d61 - std::sys::backtrace::_print_fmt
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\backtrace.rs:66
   3:     0x7ff60aab0d61 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\backtrace.rs:39
   4:     0x7ff60aad00d9 - core::fmt::rt::Argument::fmt
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\fmt\rt.rs:177
   5:     0x7ff60aad00d9 - core::fmt::write
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\fmt\mod.rs:1178
   6:     0x7ff60aaad207 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\io\mod.rs:1823
   7:     0x7ff60aab2e79 - std::panicking::default_hook::closure$1
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:266
   8:     0x7ff60aab29fc - std::panicking::default_hook
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:293
   9:     0x7ff60aab3782 - std::panicking::rust_panic_with_hook
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:797
  10:     0x7ff60aab358f - std::panicking::begin_panic_handler::closure$0
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:664
  11:     0x7ff60aab181f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\backtrace.rs:170
  12:     0x7ff60aab31d6 - std::panicking::begin_panic_handler
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
  13:     0x7ff60aad998d - core::panicking::panic_nounwind_fmt::runtime
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:112
  14:     0x7ff60aad998d - core::panicking::panic_nounwind_fmt
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:122
  15:     0x7ff60aad9a33 - core::panicking::panic_nounwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:221
  16:     0x7ff60aad9beb - core::panicking::panic_cannot_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:310
  17:     0x7ff60a6da996 - tacky_borders::window_border::WindowBorder::s_wnd_proc
                               at C:\Users\USER\Desktop\tacky-borders-main\src\window_border.rs:353
  18:     0x7fffe95bf540 - _CxxFrameHandler3
  19:     0x7fffe95b33d8 - is_exception_typeof
  20:     0x7ffffbf63846 - RtlCaptureContext2
  21:     0x7ff60a6da956 - tacky_borders::window_border::WindowBorder::s_wnd_proc
                               at C:\Users\USER\Desktop\tacky-borders-main\src\window_border.rs:367
  22:     0x7ffffbab5801 - CallWindowProcW
  23:     0x7ffffbab334d - IsWindowUnicode
  24:     0x7ff60a715cff - windows::Win32::UI::WindowsAndMessaging::DispatchMessageW
                               at C:\Users\USER\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.58.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:772
  25:     0x7ff60a6d954d - tacky_borders::window_border::WindowBorder::init
                               at C:\Users\USER\Desktop\tacky-borders-main\src\window_border.rs:144
  26:     0x7ff60a74a4ed - tacky_borders::utils::create_border_for_window::closure$0
                               at C:\Users\USER\Desktop\tacky-borders-main\src\utils.rs:255
  27:     0x7ff60a7481de - core::hint::black_box
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\hint.rs:388
  28:     0x7ff60a7481de - std::sys::backtrace::__rust_begin_short_backtrace<tacky_borders::utils::create_border_for_window::closure_env$0,tuple$<> >
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\sys\backtrace.rs:154
  29:     0x7ff60a71ff9e - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0<tacky_borders::utils::create_border_for_window::closure_env$0,tuple$<> >
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\thread\mod.rs:522
  30:     0x7ff60a70a25e - core::panic::unwind_safe::impl$25::call_once<tuple$<>,std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tacky_borders::utils::create_border_for_window::closure_env$0,tuple$<> > >
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\panic\unwind_safe.rs:272
  31:     0x7ff60a720695 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<tacky_borders::utils::create_border_for_window::closure_env$0,tuple$<> > >,tuple$<> >
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\panicking.rs:554
  32:     0x7ff60a720263 - std::thread::impl$0::spawn_unchecked_::closure$0::closure$0<tacky_borders::utils::destroy_border_for_window::closure_env$0,tuple$<> >
  33:     0x7ff60a71f255 - std::panicking::try
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\panicking.rs:518
  34:     0x7ff60a71f255 - std::panic::catch_unwind
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\panic.rs:345
  35:     0x7ff60a71f255 - std::thread::impl$0::spawn_unchecked_::closure$1<tacky_borders::utils::create_border_for_window::closure_env$0,tuple$<> >
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\std\src\thread\mod.rs:521
  36:     0x7ff60a6d16be - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<tacky_borders::utils::create_border_for_window::closure_env$0,tuple$<> >,tuple$<> >
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ops\function.rs:250
  37:     0x7ff60aabe58d - alloc::boxed::impl$48::call_once
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/alloc\src\boxed.rs:2231
  38:     0x7ff60aabe58d - alloc::boxed::impl$48::call_once
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/alloc\src\boxed.rs:2231
  39:     0x7ff60aabe58d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\pal\windows\thread.rs:55
  40:     0x7ffffa67e8d7 - BaseThreadInitThunk
  41:     0x7ffffbf1fbcc - RtlUserThreadStart
thread caused non-unwinding panic. aborting.`

**Comment by lukeyou05** [comment]
Yeah, this is a known issue. More specifically, it will crash when you use two gradients with a different number of colors. For now, you should be able to set them both to have three colors and it should work?

**Comment by RTFTR** [comment]
> Yeah, this is a known issue. More specifically, it will crash when you use gradients for both the active and inactive color, but with a different number of colors in each gradient. For now, you should be able to set them both to have three colors and it should work?

Thanks for the reply, With the same numbers of colors for both, It works flawlessly.
Also, The context menu on the tray won't display when i set the task scheduler like this
![image](https://github.com/user-attachments/assets/a99c3bf2-fc7b-463a-b813-1817dbd449d2)

**Comment by lukeyou05** [comment]
I can't seem to reproduce the tray icon issue. Do you have any other steps to reproduce it?

**Comment by RTFTR** [comment]
Did you restart your PC after you set the "At log on" in triggers?

**Comment by lukeyou05** [comment]
I did, and I had "Run with highest privileges" enabled as well.

**Comment by RTFTR** [comment]
> I did, and I had "Run with highest privileges" enabled as well.

Hmm then it seems to be my end, thanks for the reply

**Comment by RTFTR** [comment]
Oh and one more thing, There's an issue where all windows except for the ones maximized become blackout. Not sure if I launched the app as an administrator

**Comment by lukeyou05** [comment]
Not sure what you mean. Can you send a pic?
