### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by kleineluka** [lukeyou05/tacky-borders#9]
Just cloned and did a standard cargo build. Attached the log here since it's huge but I can paste it as a comment if that's preferred. I should have everything needed (?), including Rust and MSVC. 

[Error.txt](https://github.com/user-attachments/files/17878154/Error.txt)

**Comment by lukeyou05** [comment]
It seems like you're running an old version of Rust. Can you try updating it via `rustup update`?

**Comment by kleineluka** [comment]
Ah sorry about that, a little embarrassing lol. However now I'm having trouble with the built exe - it runs but instantly closes, not having an effect or creating the config file. Not sure what exactly I am doing wrong. I was wanting to build it to try out the new gradient / animations :)

**Comment by kleineluka** [comment]
Found the issue. It logs before it creates the config dir (which I presume wouldn't be an issue if upgrading from an old version where config dir is made) with no error handling. I fixed it by, in `border_config.rs`, moving the logic to create the directory from `create_config` to `get_config_location`. Here is what my (working) `get_config_location` looks like:

``` rust
 pub fn get_config_location() -> PathBuf {
        let home_dir = home_dir().expect("can't find home path");
        let config_dir = home_dir.join(".config").join("tacky-borders");
        if !config_dir.exists() {
            DirBuilder::new()
                .recursive(true)
                .create(&config_dir)
                .expect("could not create config directory!");
        }
        config_dir
    }```
    
And of course the redundant check can then be removed from `create_config`. There's a million ways to fix this, so I can submit a PR, you can copy this, do it your own way, or just close this issue.

**Comment by lukeyou05** [comment]
Oh wow, total oversight on my part lol. Sorry about that. Feel free to create a PR!
